package MainPackage;
import FileMenu.search;
import UserSetting.TimeDate;
import SomeFunctions.MyConnection;
import UserSetting.Background;
import UserSetting.LoginFrame;
import UserSetting.UserSetting;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public final class MainFrame extends javax.swing.JFrame {
    
    public MainFrame() {   
        
        initComponents();      
        this.setLocationRelativeTo(null);         
        setResizable(false);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        jLabelBackround = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemGreen = new javax.swing.JMenuItem();
        jMenuItemWhite = new javax.swing.JMenuItem();
        jMenuItemDefault = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuSearch = new javax.swing.JMenuItem();
        jMenuSignOut = new javax.swing.JMenuItem();
        jMenuEx = new javax.swing.JMenuItem();
        jMenuAddnewincident = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Community Incident Report");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(153, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBackround.setBackground(new java.awt.Color(204, 102, 255));
        jLabelBackround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cases (2).png"))); // NOI18N
        getContentPane().add(jLabelBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 880, 410));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Back.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 820, 450));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFocusCycleRoot(true);
        jMenuBar1.setFocusTraversalPolicyProvider(true);
        jMenuBar1.setFocusable(false);
        jMenuBar1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(322, 40));

        jMenu7.setForeground(new java.awt.Color(51, 51, 51));
        jMenu7.setText("File                 ");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/settingUser.png"))); // NOI18N
        jMenuItem4.setText("User Setting");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/setting.png"))); // NOI18N
        jMenuItem5.setText("Time & Date");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/color.png"))); // NOI18N
        jMenu2.setText("Background");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItemGreen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemGreen.setText("Change Background ");
        jMenuItemGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGreenActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemGreen);

        jMenuItemWhite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemWhite.setText("White");
        jMenuItemWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWhiteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemWhite);

        jMenuItemDefault.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemDefault.setForeground(new java.awt.Color(0, 102, 0));
        jMenuItemDefault.setText("Default");
        jMenuItemDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDefaultActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDefault);

        jMenu7.add(jMenu2);

        jMenuBar1.add(jMenu7);

        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Settings           ");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N

        jMenuSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/sea.png"))); // NOI18N
        jMenuSearch.setText("Reports");
        jMenuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSearch);

        jMenuSignOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuSignOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/signOut.png"))); // NOI18N
        jMenuSignOut.setText("SignOut");
        jMenuSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSignOutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSignOut);

        jMenuEx.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuEx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ex.png"))); // NOI18N
        jMenuEx.setText("Exit");
        jMenuEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuEx);

        jMenuBar1.add(jMenu1);

        jMenuAddnewincident.setBackground(new java.awt.Color(204, 255, 204));
        jMenuAddnewincident.setForeground(new java.awt.Color(51, 51, 51));
        jMenuAddnewincident.setText("Investigation");
        jMenuAddnewincident.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuAddnewincident.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jMenuAddnewincident.setMaximumSize(new java.awt.Dimension(220, 32767));
        jMenuAddnewincident.setMinimumSize(new java.awt.Dimension(106, 36));
        jMenuAddnewincident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddnewincidentActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Result.png"))); // NOI18N
        jMenuItem1.setText("View Incidents");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAddnewincident.add(jMenuItem1);

        jMenuBar1.add(jMenuAddnewincident);

        jMenu5.setForeground(new java.awt.Color(51, 51, 51));
        jMenu5.setText(" About            ");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Frame frame = new Frame();
    ReportGUI searchO = new ReportGUI();
    UserSetting us = new UserSetting();
    IncidentGUI manageO = new IncidentGUI();
    ResultTable rt = new ResultTable();
    LoginFrame Login = new LoginFrame();
    private void jMenuExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExActionPerformed

    private void jMenuSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSignOutActionPerformed
        this.dispose();
        frame.dispose();
        tt.dispose();
        Back.dispose();
        rt.dispose();
        us.dispose();
        searchO.dispose();
        manageO.dispose();
        Login.setVisible(true);
        Login.pack();
        Login.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jMenuSignOutActionPerformed

    private void jMenuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSearchActionPerformed
        searchO.setVisible(true);
        searchO.pack();
        searchO.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuSearchActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
     
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        About about = new About();
        about.setVisible(true);
        about.pack();
        about.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu5MouseClicked
        
        int a = 2;        
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        String Query = "SELECT loginAs FROM login WHERE loginAs ='Barangay Secretary'";
        PreparedStatement ps;
        ResultSet rs;
        try{
            ps = MyConnection.getConnection().prepareStatement(Query);
            rs = ps.executeQuery();
            rs.next();
            if(rs.getString("loginAs").equals(LoginFrame.SeeUser)){
                us.setVisible(true);
                us.setLocationRelativeTo(null);
            }else
                JOptionPane.showMessageDialog(null, "Only Admin Can Manipulate User Setting!");    
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Please Try After Some Time!"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginAsTeacher();
        LoginAsStudent();
    }//GEN-LAST:event_formWindowOpened
        TimeTable tt = new TimeTable();        Background Back = new Background();
    private void jMenuItemGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGreenActionPerformed
        Back.setVisible(true);
        Back.pack();
        Back.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jMenuItemGreenActionPerformed

    private void jMenuItemWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWhiteActionPerformed
       
        jLabelBackround.setIcon(new ImageIcon("/home/NetBeansProjects/student/src/Picture/ba.jpeg"));
    }//GEN-LAST:event_jMenuItemWhiteActionPerformed

    private void jMenuItemDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDefaultActionPerformed
      jLabelBackground.setIcon(new ImageIcon("/home/NetBeansProjects/student/src/Picture/Back.jpg"));
    }//GEN-LAST:event_jMenuItemDefaultActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        TimeDate time = new TimeDate();
        time.setVisible(true);
        time.setLocationRelativeTo(null);
        time.pack();;
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    // 
    private void jMenuAddnewincidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddnewincidentActionPerformed
        // TODO add your handling code here:
        investigation.setVisible(true);
        investigation.pack();
        investigation.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuAddnewincidentActionPerformed

    // Dito i code mo ano lalabas
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
       IncidentGUI reg = new IncidentGUI();
       reg.setVisible(true);
       reg.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void LoginAsStudent(){
        // ======================When YOu Login As Student =============================
        String Query = "SELECT loginAs FROM login WHERE loginAs ='Student'";
        PreparedStatement ps;
        ResultSet rs;
        try{
            ps = MyConnection.getConnection().prepareStatement(Query);
            rs = ps.executeQuery();
            rs.next();
            if(LoginFrame.SeeUser.equals(rs.getString("loginAs"))){
 
                jMenuAddnewincident.setEnabled(false);
              
            }
        }catch(Exception e){
        }
// =============================================================================
    }
    private void LoginAsTeacher(){
        // ======================When YOu Login As Teacher =============================
        String Query2 = "SELECT loginAs FROM login WHERE loginAs ='Teacher'";
        PreparedStatement s;
        ResultSet r;
        try{
            s = MyConnection.getConnection().prepareStatement(Query2);
            r = s.executeQuery();
            r.next();
            if(LoginFrame.SeeUser.equals(r.getString("loginAs"))){
                
            }
             }
        catch(Exception e){
            
        }
// =============================================================================
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBackround;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenuAddnewincident;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEx;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemDefault;
    private javax.swing.JMenuItem jMenuItemGreen;
    private javax.swing.JMenuItem jMenuItemWhite;
    private javax.swing.JMenuItem jMenuSearch;
    private javax.swing.JMenuItem jMenuSignOut;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
